version: "3.9"
services:
  notes-postgres:
    container_name: notes-postgres
    image: postgres:15.2
    environment:
      POSTGRES_DB: "notes_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "12345"
    ports:
      - "5432:5432"
    networks:
      - notes

networks:
  notes:
    driver: bridge